services:
  - type: web
    name: matchproof
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npx prisma generate && npm run build
    startCommand: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_NAME
        value: MatchProof
      - key: NEXT_PUBLIC_APP_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: ENABLE_DEMO_MODE
        value: "false"
      - key: ENABLE_PUBLIC_EXPORT
        value: "false"
