services:
  - type: web
    name: matchproof
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npx prisma generate && npm run build
    startCommand: sh -c "npx prisma migrate deploy && npx prisma db seed && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_NAME
        value: MatchProof
      - key: NEXT_PUBLIC_APP_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: ENABLE_DEMO_MODE
        value: "true"
      - key: ENABLE_PUBLIC_EXPORT
        value: "false"
      - key: TXLINE_NETWORK
        value: mainnet
      - key: TXLINE_SERVICE_LEVEL
        value: "12"
      - key: TXLINE_API_ORIGIN
        value: https://txline.txodds.com
      - key: TXLINE_API_BASE_URL
        value: https://txline.txodds.com/api
      - key: SOLANA_RPC_URL
        value: https://api.mainnet-beta.solana.com
      - key: TXLINE_PROGRAM_ID
        value: 9ExbZjAapQww1vfcisDmrngPinHTEfpjYRWMunJgcKaA
      - key: TXLINE_TXL_TOKEN_MINT
        value: Zhw9TVKp68a1QrftncMSd6ELXKDtpVMNuMGr1jNwdeL
      - key: TXLINE_GUEST_JWT
        sync: false
      - key: TXLINE_API_TOKEN
        sync: false
      - key: MATCHPROOF_OPERATOR_KEY
        sync: false
