export const DEMO_MODE_LABEL = "DEMO MODE - SEEDED FALLBACK DATA";

const baseTime = "2026-07-04T15:00:00.000Z";

export const demoFixture = {
  fixtureId: "mp-demo-fixture-001",
  competitionId: "world-cup-demo",
  participant1: "Japan",
  participant2: "Croatia",
  participant1IsHome: true,
  startTime: baseTime,
  status: "live",
  raw: {
    FixtureId: "mp-demo-fixture-001",
    CompetitionId: "world-cup-demo",
    Participant1: "Japan",
    Participant2: "Croatia",
    Participant1IsHome: true,
    StartTime: baseTime,
    Status: "live",
    demoMode: true,
    label: DEMO_MODE_LABEL,
  },
};

export const demoFeedUpdates = [
  {
    id: "demo-update-001",
    sequence: "1001",
    providerTimestamp: "2026-07-04T15:00:05.000Z",
    ingestedAt: "2026-07-04T15:00:06.000Z",
    sourceMode: "seed",
    raw: {
      fixtureId: demoFixture.fixtureId,
      seq: 1001,
      status: "first_half",
      period: "1H",
      score: { listedHome: 0, listedAway: 0 },
      providerTimestamp: "2026-07-04T15:00:05.000Z",
      label: DEMO_MODE_LABEL,
    },
  },
  {
    id: "demo-update-002",
    sequence: "1002",
    providerTimestamp: "2026-07-04T15:18:11.000Z",
    ingestedAt: "2026-07-04T15:18:12.000Z",
    sourceMode: "seed",
    raw: {
      fixtureId: demoFixture.fixtureId,
      seq: 1002,
      status: "first_half",
      period: "1H",
      score: { listedHome: 1, listedAway: 0 },
      providerTimestamp: "2026-07-04T15:18:11.000Z",
      statKey: "1002",
      label: DEMO_MODE_LABEL,
    },
  },
  {
    id: "demo-update-003",
    sequence: "1002",
    providerTimestamp: "2026-07-04T15:18:11.000Z",
    ingestedAt: "2026-07-04T15:18:14.000Z",
    sourceMode: "seed",
    raw: {
      fixtureId: demoFixture.fixtureId,
      seq: 1002,
      status: "first_half",
      period: "1H",
      score: { listedHome: 1, listedAway: 0 },
      providerTimestamp: "2026-07-04T15:18:11.000Z",
      duplicateOf: "demo-update-002",
      label: DEMO_MODE_LABEL,
    },
  },
  {
    id: "demo-update-004",
    sequence: "1003",
    providerTimestamp: "2026-07-04T15:47:00.000Z",
    ingestedAt: "2026-07-04T15:47:02.000Z",
    sourceMode: "seed",
    raw: {
      fixtureId: demoFixture.fixtureId,
      seq: 1003,
      status: "halftime",
      period: "HT",
      score: { listedHome: 1, listedAway: 0 },
      providerTimestamp: "2026-07-04T15:47:00.000Z",
      label: DEMO_MODE_LABEL,
    },
  },
  {
    id: "demo-update-005",
    sequence: "1004",
    providerTimestamp: "2026-07-04T16:09:20.000Z",
    ingestedAt: "2026-07-04T16:11:45.000Z",
    sourceMode: "seed",
    raw: {
      fixtureId: demoFixture.fixtureId,
      seq: 1004,
      status: "second_half",
      period: "2H",
      score: { listedHome: 1, listedAway: 1 },
      providerTimestamp: "2026-07-04T16:09:20.000Z",
      delayedSeconds: 145,
      label: DEMO_MODE_LABEL,
    },
  },
];

export const demoSignals = [
  {
    id: "demo-signal-001",
    agentType: "match_state",
    severity: "low",
    title: "Score state changed",
    summary: "Fixture score changed from 0-0 to 1-0.",
    sourceUpdateIds: ["demo-update-001", "demo-update-002"],
    evidence: {
      previousScore: "0-0",
      nextScore: "1-0",
      updateSequence: "1002",
      label: DEMO_MODE_LABEL,
    },
    createdAt: "2026-07-04T15:18:12.000Z",
  },
  {
    id: "demo-signal-002",
    agentType: "feed_health",
    severity: "low",
    title: "Duplicate score update detected",
    summary: "The same fixture sequence was received twice and linked to the original update.",
    sourceUpdateIds: ["demo-update-002", "demo-update-003"],
    evidence: {
      sequence: "1002",
      duplicateUpdateId: "demo-update-003",
      originalUpdateId: "demo-update-002",
      label: DEMO_MODE_LABEL,
    },
    createdAt: "2026-07-04T15:18:14.000Z",
  },
  {
    id: "demo-signal-003",
    agentType: "match_state",
    severity: "low",
    title: "Period changed",
    summary: "Fixture period changed from first half to halftime.",
    sourceUpdateIds: ["demo-update-003", "demo-update-004"],
    evidence: {
      previousPeriod: "1H",
      nextPeriod: "HT",
      updateSequence: "1003",
      label: DEMO_MODE_LABEL,
    },
    createdAt: "2026-07-04T15:47:02.000Z",
  },
  {
    id: "demo-signal-004",
    agentType: "feed_health",
    severity: "medium",
    title: "Score stream delay detected",
    summary: "The update arrived 145 seconds after the provider timestamp.",
    sourceUpdateIds: ["demo-update-005"],
    evidence: {
      delayedSeconds: 145,
      thresholdSeconds: 90,
      updateSequence: "1004",
      label: DEMO_MODE_LABEL,
    },
    createdAt: "2026-07-04T16:11:45.000Z",
  },
];

export const demoVerification = {
  id: "demo-verification-001",
  fixtureId: demoFixture.fixtureId,
  sourceUpdateId: "demo-update-002",
  statKey: "1002",
  sequence: "1002",
  network: "devnet",
  status: "unsupported",
  proof: {
    demoMode: true,
    label: DEMO_MODE_LABEL,
    note: "Seeded placeholder. This is not a Solana verification result.",
  },
  result: {
    verified: false,
    reason: "TxLINE credentials or proof data are required for real validation.",
  },
};

export const demoAuditLogs = [
  {
    level: "info",
    eventType: "app_started",
    message: "MatchProof demo runtime initialized.",
    createdAt: "2026-07-04T15:00:00.000Z",
    metadata: { label: DEMO_MODE_LABEL },
  },
  {
    level: "info",
    eventType: "fixture_snapshot_fetched",
    message: "Seeded fixture snapshot loaded for demo mode.",
    createdAt: "2026-07-04T15:00:03.000Z",
    metadata: { fixtureId: demoFixture.fixtureId, sourceMode: "seed" },
  },
  {
    level: "info",
    eventType: "score_update_stored",
    message: "Score update sequence 1002 stored.",
    createdAt: "2026-07-04T15:18:12.000Z",
    metadata: { updateId: "demo-update-002" },
  },
  {
    level: "warning",
    eventType: "agent_signal_created",
    message: "Feed Health Agent created a duplicate update signal.",
    createdAt: "2026-07-04T15:18:14.000Z",
    metadata: { signalId: "demo-signal-002" },
  },
  {
    level: "info",
    eventType: "verification_requested",
    message: "Demo proof placeholder prepared for score/stat validation.",
    createdAt: "2026-07-04T15:19:00.000Z",
    metadata: { verificationId: demoVerification.id },
  },
];
